"""Add updated_at column to lab_orders

Revision ID: 0b6dfa7a7693
Revises: f2cad7a9de74
Create Date: 2025-08-24 20:41:00.086429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b6dfa7a7693'
down_revision: Union[str, Sequence[str], None] = 'f2cad7a9de74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
