"""Add updated_at column to lab_orders

Revision ID: f2cad7a9de74
Revises: ac02927f235c
Create Date: 2025-08-24 20:38:29.645225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2cad7a9de74'
down_revision: Union[str, Sequence[str], None] = 'ac02927f235c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lab_orders', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lab_orders', 'updated_at')
    # ### end Alembic commands ###
