"""Add consultation_fee to staff

Revision ID: 5c3bf9bbdec3
Revises: 0b6dfa7a7693
Create Date: 2025-08-24 23:51:19.722594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c3bf9bbdec3'
down_revision: Union[str, Sequence[str], None] = '0b6dfa7a7693'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff', sa.Column('consultation_fee', sa.Numeric(precision=10, scale=3), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff', 'consultation_fee')
    # ### end Alembic commands ###
