"""Add discount and rejection features

Revision ID: ceec024a8a2f
Revises: b82d7d579305
Create Date: 2025-08-25 04:38:29.200074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ceec024a8a2f'
down_revision: Union[str, Sequence[str], None] = 'b82d7d579305'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'is_rejected')
    op.drop_column('invoices', 'rejection_reason')
    op.add_column('lab_orders', sa.Column('rejection_reason', sa.Text(), nullable=True))
    op.add_column('radiology_orders', sa.Column('rejection_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('radiology_orders', 'rejection_reason')
    op.drop_column('lab_orders', 'rejection_reason')
    op.add_column('invoices', sa.Column('rejection_reason', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('is_rejected', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
